FROM coreoasis/oasis_base:latest

RUN mkdir -p /tmp/autodoc/modules
COPY ./src /tmp/autodoc/src
COPY ["./docker/entrypoint_build.sh", \
      "Makefile", \
      "/tmp/"]

WORKDIR /tmp/
CMD ./entrypoint_build.sh
