name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}


jobs:
  deploy-preview:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26  # v3.7.0

      - name: Set up Python 3.11
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c  # v4.9.1
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt

      - name: Build
        run: ./build.sh

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@ffa7509e91a3ec8dfc2e5536c4d5c1acdf7a6de9  # v1.8.1
        with:
          source-dir: ./build/html
          deploy-repository: OasisLMF/PreviewDocs
          token: ${{ secrets.BUILD_PREVIEW_TOKEN }}
